# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim-buster

COPY bot/requirements.txt /bot/requirements.txt
RUN pip install -r bot/requirements.txt
COPY bot /bot
# RUN pip install -r songhelper/requirements.txt
