# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim-buster

COPY server/requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
COPY server /app
# RUN pip install -r songhelper/requirements.txt
