version: '3.4'

services:
  server:
    image: songhelper-server
    container_name: server
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    restart: always
  bot:
    image: songhelper-bot
    container_name: bot
    restart: always
    environment:
      TOKEN: ${TOKEN}
