# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim-buster

COPY server/requirements.txt /app/requirements.txt
COPY server/songhelper/requirements.txt /app/requirements_ai.txt
WORKDIR /app
RUN pip install -r requirements.txt
RUN pip install -r requirements_ai.txt
COPY server /app
