# For more information, please refer to https://aka.ms/vscode-docker-python
FROM node:buster-slim

COPY mobileApp/package.json /app/package.json
WORKDIR /app
RUN npm install -g expo-cli
RUN npm i
COPY mobileApp /app
