# Generated by Django 3.1.6 on 2021-03-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('H', 'Happy'), ('E', 'Energetic'), ('C', 'Calm'), ('S', 'Sad')], max_length=1)),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Moods',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('artist', models.CharField(max_length=20, verbose_name='Artists')),
                ('song_id', models.CharField(max_length=100, unique=True, verbose_name='Id')),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('key', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesite.mood')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-name'],
            },
        ),
    ]
