# Generated by Django 3.1.7 on 2021-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.CharField(default='', max_length=50, verbose_name='Artists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='time_signature',
            field=models.FloatField(),
        ),
    ]
