# Generated by Django 3.1.8 on 2021-07-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesite', '0003_auto_20210717_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(max_length=15, verbose_name='Mood'),
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
