name: Client part CI

on:
  pull_request:
    branches: [rebuild]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
        
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./client/yarn.lock
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Lint with ESLint
      run: yarn lint:check
      
    - name: Test with Jest
      run: yarn test --coverage
