name: Server part CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, rebuild]

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pylint pytest-cov
      - name: Lint with ruff
        run: |
          ruff .
      - name: Lint with pylint
        run: |
          pylint .
      - name: Test with pytest
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
