name: Server part CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, rebuild]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          pip install ruff
          ruff server
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint server
      - name: Test with pytest
        run: |
          pytest
